spring.application.name=ParcelServer

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/parcel}
spring.datasource.username=${DATABASE_USERNAME:admin}
spring.datasource.password=${DATABASE_PASSWORD:admin}
