spring.application.name=ParcelServer
server.port=${SERVER_PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/parcel}
spring.datasource.username=${SPRING_DATASOURCE_USERRNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true

spring.data.redis.host=${SPRING_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_REDIS_PORT:6379}
spring.data.redis.database=${SPRING_REDIS_DATABASE:0}
spring.data.redis.password=${SPRING_REDIS_PASSWORD:}